# AEROSPACE CONFIG
start-at-login = true

after-login-command = []

after-startup-command = [
     'exec-and-forget /opt/homebrew/opt/borders/bin/borders active_color=0xCFEBBF83 inactive_color=0x33434c5e width=4.0'
#     'exec-and-forget /opt/homebrew/opt/sketchybar/bin/sketchybar'
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_changed FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]

on-focused-monitor-changed = [
  'move-mouse monitor-lazy-center'
]

on-focus-changed = [
  'move-mouse window-lazy-center',
  'exec-and-forget /bin/bash -c /opt/homebrew/bin/sketchybar --trigger front_app_switched',
  'exec-and-forget sketchybar --trigger update_windows'
]

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'auto'

key-mapping.preset = 'qwerty'

[gaps]
#outer.bottom numbers have to match presentation.sh variables. built-in retina display is excluded from presentation mode, so this only works on external monitors.
outer.bottom =        [{monitor.'^built-in retina display$' = 10 }, 10]
outer.top =        52
outer.left =       13
outer.right =      13
inner.horizontal = 10
inner.vertical =   10

[exec]                   # Again, you don't need to copy all config sections to your config.
inherit-env-vars = true  # If you don't touch "exec" section,
[exec.env-vars]          # it will fallback to "default-config.toml"
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'

[mode.main.binding]
#cmd-space = 'layout floating tiling'
#cmd-r = [
#  'mode resize',
#  'exec-and-forget sketchybar --trigger send_message MESSAGE="RESIZE MODE" HOLD="true"'
#]

#cmd-keypadMinus = 'resize smart -70'
#cmd-keypadPlus = 'resize smart +70'

#cmd-g = 'mode join'
#cmd-q = [
#  'close --quit-if-last-window'
#]
#cmd-w = []

# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# alt-enter = 'exec-and-forget open -n /Volumes/Macintosh\ HD/Applications/Alacritty.app'
# alt-m = 'exec-and-forget open -n /Volumes/Macintosh\ HD/Applications/Marta.app'

alt-shift-f = 'macos-native-fullscreen'
alt-f = 'fullscreen'
alt-ctrl-f = 'layout floating'

alt-g = 'split horizontal'
alt-v = 'split vertical'

alt-h = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
alt-j = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
alt-k = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
alt-l = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'
#alt-left = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop left'
#alt-down = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop down'
#alt-up = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop up'
#alt-right = 'focus --boundaries all-monitors-outer-frame --boundaries-action stop right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'
#alt-shift-left = 'move left'
#alt-shift-down = 'move down'
#alt-shift-up = 'move up'
#alt-shift-right = 'move right'

alt-1 = 'workspace 1'  # Slack
alt-2 = 'workspace 2'  # Kitty
alt-3 = 'workspace 3'  # Vscode
alt-4 = 'workspace 4'  # Dbeaver
alt-5 = 'workspace 5'  # Insomnia
alt-6 = 'workspace 6'  # Brave
alt-7 = 'workspace 7'  # Brave
alt-8 = 'workspace 8'  # Spotify
alt-9 = 'workspace 9'  # Todoist
alt-0 = 'workspace 10' # ?

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab = 'workspace-back-and-forth'
alt-p = 'move-workspace-to-monitor --wrap-around next'
#alt-shift-p = [
#  'move-node-to-monitor --wrap-around next',
# 'focus-monitor next --wrap-around' 
#]

#alt-shift-semicolon = [
#  'mode service',
# 'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"'
#]
alt-shift-semicolon = [
  'mode service',
  'exec-and-forget sketchybar --trigger send_message MESSAGE="SERVICE MODE" HOLD="true"'
]
#alt-shift-semicolon = 'mode service'

[mode.service.binding]
esc = [
 'reload-config',
 'exec-and-forget sketchybar --trigger hide_message',
 'exec-and-forget sketchybar --reload',
 'mode main'
]
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2


b = [
   'exec-and-forget ~/.config/aerospace/presentation.sh on',
   'exec-and-forget sketchybar --bar height=0',
   'exec-and-forget sketchybar --trigger hide_message',
   'mode main'
]
shift-b = [
   'exec-and-forget ~/.config/aerospace/presentation.sh off',
   'exec-and-forget sketchybar --bar height=36',
   'exec-and-forget sketchybar --trigger hide_message',
   'mode main'
]

backspace = ['close-all-windows-but-current', 'mode main']

[mode.resize.binding]
keypadMinus = 'resize smart -70'
keypadPlus = 'resize smart +70'
h = ['resize width -64']
j = ['resize height -64']
k = ['resize height +64']
l = ['resize width +64']
esc = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]
enter = [
  'mode main',
  'exec-and-forget sketchybar --trigger hide_message'
]

[mode.join.binding]
h = ['join-with left', 'mode main']
j = ['join-with down', 'mode main']
k = ['join-with up', 'mode main']
l = ['join-with right', 'mode main']


[workspace-to-monitor-force-assignment]
1 = '^built-in retina display$' 
2 = '27GN7'
3 = '27GN7'
4 = '27GN7'
5 = '27GN7'
6 = '27GN7'
7 = '27GN7'
8 = '27GN7'
9 = '27GN7'
0 = '27GN7'

[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = [
'layout floating'
]

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'              
run = ['move-node-to-workspace 2']  

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'              
run = ['move-node-to-workspace 3']  

[[on-window-detected]]
if.app-id = 'com.spotify.client'              
run = ['move-node-to-workspace 8']  

[[on-window-detected]]
if.app-id = 'com.todoist.mac.Todoist'              
run = ['move-node-to-workspace 9']  

