#!/bin/bash
PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

BAR_COLOR=0xff161821
ITEM_BG_COLOR=0xff1a1b26
ITEM_LABEL_COLOR=0xffc0caf5
ITEM_ICON_COLOR=0xff7aa2f7

bar=(
  color=$BAR_COLOR
  position=top
  height=25
  margin=10
  y_offset=5
  padding_left=2
  padding_right=2
  corner_radius=10
)

sketchybar --bar "${bar[@]}"

default=(
  background.color=$ITEM_BG_COLOR
  icon.color=$ITEM_ICON_COLOR
  label.color=$ITEM_LABEL_COLOR
  icon.font="Hack Nerd Font:Regular:14.0"
  label.font="JetBrains Mono:Regular:14.0"
  background.corner_radius=5
  background.height=26
  padding_left=10
  padding_right=10
  icon.padding_right=2
  icon.padding_left=2
)

sketchybar --default "${default[@]}"

source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/clock.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/volume.sh"


sketchybar --add event aerospace_workspace_change

for sid in $(aerospace list-workspaces --all); do
    sketchybar --add item space.$sid left \
        --subscribe space.$sid aerospace_workspace_change \
        --set space.$sid \
        width=25 \
        background.color=0x44ffffff \
        background.corner_radius=5 \
        background.height=26 \
        label="$sid" \
        click_script="aerospace workspace $sid" \
        script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done


sketchybar --update

